1. Import pandas as the object with name "pd"
2. Use the "read_html()" command to scrape the table from the website and save it as the dataframe with name "df"
3. Change "df" to be the same data frame but with the exception that the field "Neighbourhood" is never "Not assigned"
4. Print the table
5. Print the shape of the table

Link to this notebook: https://eu-gb.dataplatform.cloud.ibm.com/analytics/notebooks/v2/b6b68289-88cf-49a9-aa43-42e5f12791c5/view?access_token=e1ca19806cf7a3d0203b447d6c8e2f7f3c3472d49a7e5b9e15218f38af1f5164

In [37]:
import pandas as pd
data = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
df = data[0]
df = df[df.Neighbourhood != "Not assigned"]
df.reset_index(drop=True, inplace=True)
df

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [28]:
print(df.shape)

(103, 3)